name: flame_menu_4games
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI + BASIC
  cupertino_icons: ^1.0.8
  collection: ^1.17.0
  shared_preferences: ^2.1.1
  path_provider: ^2.0.14

  # FLAME ENGINE
  flame: ^1.32.0
  flame_tiled: ^3.0.7

  # ANIMATION
  lottie: ^3.3.1
  rive: ^0.13.20
  flame_rive: ^1.10.19

  # LOCAL SPINE 3.8 RUNTIME (FIXED PATH)
  spine38_runtime:
    path: spine38_runtime

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/game/
    - assets/images/game/background/
    - assets/spine/
    - assets/tiles/
    - assets/rive/
